backend:
  name: github
  repo: gitbreaker222/2024-rl-dev
  branch: main
  site_domain: cms.netlify.com
media_folder: "static/images/uploads"
public_folder: "/images/uploads"
collections:
  - name: pages
    label: Single Pages
    icon: edit_document
    files:
      - label: about
        name: About me
        file: "src/routes/+page.md"
        fields:
          - {label: Content, name: content, widget: markdown}
      - label: "Test Page"
        name: "test"
        file: "src/routes/test/+page.md"
        fields:
          - {label: Published, name: isPublic, widget: boolean}
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
          - label: Team
            required: false
            name: team
            widget: list
            fields:
              - { label: "Body", name: "body", widget: "markdown" }
  - divider: true
    name: d1
    files: []
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "src/routes/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}/+page" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { label: "Rating (scale of 1-5)", name: "rating", widget: "number" }
      - { label: "Body", name: "body", widget: "markdown" }